### ISSUE TITLE
How the incoming PSTN call is bridged?

### ISSUE THREAD

**Issue by oripwk** [ulifigueroa/tokbox-twilio#1]
https://github.com/ulifigueroa/tokbox-twilio/blob/3e2f416f2777376459b0bc6bd31e3c249a825f18/app.js#L103

When you use OpenTok `dial(…)`, how the incoming PSTN Twilio call gets bridged to OpenTok?

Currently you have the following flow:

> _/pstn -> /gather -> opentok.dial(…) -> /enqueue -> /wait_

When you dial to OpenTok, there is no indication that the outoging call is connected in anyway to the call that is currently waiting. It looks like a completely different call getting made.

So how the incoming PSTN call gets bridged to an OpenTok session?

Thanks

**Comment by oripwk** [comment]
Okay I solved it. The answer is as follows:
* You need to establish both a SIP Trunk _and_ a SIP Domain on Twilio.
* The SIP Trunk is for creating a webhook for incoming PSTN calls.
* The SIP Domain is when the `openTok.dial(…)` gets used.
* The SIP Domain has a webhook which is attached to the app's `/sip` endpoint, where it's bridged with the incoming call using Twilio's queuing functionality.

**Comment by ulifigueroa** [comment]
Yeah, you're right Ori, it's tricky since Tokbox doesn't allow incoming calls. I'll update the documentation so this is clear.
